---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: buckit
  name: buckit
spec:
  replicas: 1
  selector:
    app: buckit
    deploymentconfig: buckit
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: buckit
        deploymentconfig: buckit
    spec:
      containers:
      - image: jhjaggars/buckit:latest
        imagePullPolicy: Always
        name: buckit
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        env:
        - name: BOOT
          value: "kafka:29092"
        - name: BUCKET_MAP_FILE
          value: "/tmp/buckets.json"
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - buckit
        from:
          kind: ImageStreamTag
          name: buckit:latest
      type: ImageChange
