apiVersion: v1
kind: Service
metadata:
  labels:
    app: buckit
  name: buckit
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: buckit
    deploymentconfig: buckit
  sessionAffinity: None
  type: ClusterIP
